name: pomodoro_genie
description: A Flutter web Pomodoro timer and task management application
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # HTTP Client for API integration
  http: ^1.1.2
  dio: ^5.4.0

  # Cross-platform storage
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Connectivity
  connectivity_plus: ^5.0.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  retrofit_generator: ^7.0.8

  # Testing
  patrol: ^3.15.2
  mockito: ^5.4.4

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700