-- Drop reminders table and related objects
DROP FUNCTION IF EXISTS dismiss_reminder(UUID, TIMESTAMP WITH TIME ZONE);
DROP FUNCTION IF EXISTS snooze_reminder(UUID, TIMESTAMP WITH TIME ZONE);
DROP FUNCTION IF EXISTS mark_reminder_failed(UUID, TEXT, TIMESTAMP WITH TIME ZONE);
DROP FUNCTION IF EXISTS mark_reminder_sent(UUID, TIMESTAMP WITH TIME ZONE);
DROP FUNCTION IF EXISTS get_ready_snoozed_reminders(TIMESTAMP WITH TIME ZONE, INTEGER);
DROP FUNCTION IF EXISTS get_due_reminders(TIMESTAMP WITH TIME ZONE, INTEGER);
DROP TRIGGER IF EXISTS update_reminders_updated_at ON reminders;
DROP TABLE IF EXISTS reminders CASCADE;