run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: pomodoro-backend
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
    enable-all: true
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  gofumpt:
    extra-rules: true
  godox:
    keywords:
      - TODO
      - BUG
      - FIXME
      - NOTE
      - HACK

linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - godox

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: internal/models
      linters:
        - maligned
  exclude:
    - "should have comment or be unexported"
    - "comment on exported .* should be of the form"