// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<Record<string, number>>;

export function GetTimerStatus():Promise<main.TimerStatus>;

export function PauseTimer():Promise<main.TimerStatus>;

export function StartTimer():Promise<main.TimerStatus>;

export function StopTimer():Promise<main.TimerStatus>;

export function UpdateSettings(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;
