// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTimerStatus() {
  return window['go']['main']['App']['GetTimerStatus']();
}

export function PauseTimer() {
  return window['go']['main']['App']['PauseTimer']();
}

export function StartTimer() {
  return window['go']['main']['App']['StartTimer']();
}

export function StopTimer() {
  return window['go']['main']['App']['StopTimer']();
}

export function UpdateSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2, arg3, arg4);
}
