name: Build All Platforms

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在版本标签时构建所有平台
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Build Web
        run: |
          cd mobile
          flutter pub get
          flutter build web --release

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-genie-web
          path: mobile/build/web/
          retention-days: 30

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Build Android APK
        run: |
          cd mobile
          flutter pub get
          flutter build apk --release

      - name: Build Android App Bundle
        run: |
          cd mobile
          flutter build appbundle --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-genie-android-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30

      - name: Upload App Bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-genie-android-aab
          path: mobile/build/app/outputs/bundle/release/app-release.aab
          retention-days: 30

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Build iOS (No Code Sign)
        run: |
          cd mobile
          flutter pub get
          flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd mobile/build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r pomodoro_genie.ipa Payload
          mv pomodoro_genie.ipa ../../../

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-genie-ios-ipa
          path: mobile/pomodoro_genie.ipa
          retention-days: 30

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Build macOS
        run: |
          cd mobile
          flutter config --enable-macos-desktop
          flutter pub get
          flutter create --platforms=macos .
          flutter build macos --release

      - name: Create DMG
        run: |
          cd mobile/build/macos/Build/Products/Release
          mkdir -p dmg_temp
          cp -r pomodoro_genie.app dmg_temp/
          hdiutil create -volname "Pomodoro Genie" -srcfolder dmg_temp -ov -format UDZO pomodoro_genie.dmg
          mv pomodoro_genie.dmg ../../../../../

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-genie-macos-dmg
          path: mobile/pomodoro_genie.dmg
          retention-days: 30

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Build Windows
        run: |
          cd mobile
          flutter config --enable-windows-desktop
          flutter pub get
          flutter create --platforms=windows .
          flutter build windows --release

      - name: Create Windows ZIP
        run: |
          cd mobile/build/windows/x64/runner/Release
          Compress-Archive -Path * -DestinationPath ../../../../../pomodoro_genie_windows.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-genie-windows
          path: mobile/pomodoro_genie_windows.zip
          retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Build Linux
        run: |
          cd mobile
          flutter config --enable-linux-desktop
          flutter pub get
          flutter create --platforms=linux .
          flutter build linux --release

      - name: Create Linux tar.gz
        run: |
          cd mobile/build/linux/x64/release/bundle
          tar -czf ../../../../../pomodoro_genie_linux.tar.gz *

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: pomodoro-genie-linux
          path: mobile/pomodoro_genie_linux.tar.gz
          retention-days: 30

  create-release:
    needs: [build-web, build-android, build-ios, build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pomodoro-genie-web/**
            pomodoro-genie-android-apk/**
            pomodoro-genie-android-aab/**
            pomodoro-genie-ios-ipa/**
            pomodoro-genie-macos-dmg/**
            pomodoro-genie-windows/**
            pomodoro-genie-linux/**
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
