name: Flutter Web CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        cd mobile
        flutter pub get
    
    - name: Analyze code
      run: |
        cd mobile
        flutter analyze
    
    - name: Run tests
      run: |
        cd mobile
        flutter test
    
    - name: Build web
      run: |
        cd mobile
        flutter build web --release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flutter-web-build
        path: mobile/build/web/
        retention-days: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        cd mobile
        flutter pub get
    
    - name: Build web for production
      run: |
        cd mobile
        flutter build web --release --web-renderer html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: mobile/build/web
        cname: pomodoro-genie.yangsuiyun.com
